services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./apps/web/config/local.json
        target: /usr/src/symbology/apps/web/config/local.json
