name: Test geo symbology packages and playwright integration tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Enable corepack
        run: corepack enable
      - name: Insall npm packages
        run: yarn install --frozen-lockfile
      - name: Install system wide playwright dependencies
        run: npx playwright install --with-deps
      - name: Lint
        run: yarn lint
      - name: Run all tests
        run: yarn test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
