name: publish docker image

on:
  push:
    branches:
      - "main"
    
    # TODO - create docker images with these as custom tag.
    tags:
      - v*
  
  pull_request:
    # Run Tests when changes are made to the Docker file
    paths:
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ github.repository_owner }}/${{ github.event.repository.name }}
            # ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          tags: |
            # set the latest tag for main branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # -
      #   name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Check if docker instruction manual changed
        id: docker-manual-changed
        uses: tj-actions/changed-files@v34
        with:
          files: |
            docs/user-docker-image.md
      -
        name: Update repo description
        if: steps.docker-manual-changed.outputs.any_changed == 'true'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: ${{ github.repository_owner }}/${{ github.event.repository.name }}
          readme-filepath: docs/user-docker-image.md
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
